/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include "main.h"
#include <string.h>

uint8_t	cnt = 0;
char led_num = 0x003F;

void set_led_num(uint8_t cnt)
{
	switch (cnt)
	{
	case 0:
		led_num = 0x003F;
		break;
	case 1:
		led_num = 0x0006;
		break;
	case 2:
		led_num = 0x005B;
		break;
	case 3:
		led_num = 0x004F;
		break;
	case 4:
		led_num = 0x0066;
		break;
	case 5:
		led_num = 0x006D;
		break;
	case 6:
		led_num = 0x007D;
		break;
	case 7:
		led_num = 0x0007;
		break;
	case 8:
		led_num = 0x007F;
		break;
	case 9:
		led_num = 0x006F;
		break;
	}

	SET_LED_NUM(led_num);
}

void init_led_num(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;	/*	Включаем тактирование порта C	*/
	GPIOC->CRL &=~GPIO_CRL_CNF0;		/*	CNF=00 для 0 пина	*/
	GPIOC->CRL |= GPIO_CRL_MODE0;		/*	MODE=11, Output 50 для 5 пина	*/
	GPIOC->CRL &=~GPIO_CRL_CNF1;		/*	CNF=00 для 1 пина	*/
	GPIOC->CRL |= GPIO_CRL_MODE1;		/*	MODE=11, Output 50 для 5 пина	*/
	GPIOC->CRL &=~GPIO_CRL_CNF2;		/*	CNF=00 для 2 пина	*/
	GPIOC->CRL |= GPIO_CRL_MODE2;		/*	MODE=11, Output 50 для 5 пина	*/
	GPIOC->CRL &=~GPIO_CRL_CNF3;		/*	CNF=00 для 3 пина	*/
	GPIOC->CRL |= GPIO_CRL_MODE3;		/*	MODE=11, Output 50 для 5 пина	*/
	GPIOC->CRL &=~GPIO_CRL_CNF4;		/*	CNF=00 для 4 пина	*/
	GPIOC->CRL |= GPIO_CRL_MODE4;		/*	MODE=11, Output 50 для 5 пина	*/
	GPIOC->CRL &=~GPIO_CRL_CNF5;		/*	CNF=00 для 5 пина	*/
	GPIOC->CRL |= GPIO_CRL_MODE5;		/*	MODE=11, Output 50 для 5 пина	*/
	GPIOC->CRL &=~GPIO_CRL_CNF6;		/*	CNF=00 для 6 пина	*/
	GPIOC->CRL |= GPIO_CRL_MODE6;		/*	MODE=11, Output 50 для 5 пина	*/
}


const uint16_t reset_value = 0x7FFF;
static void init_decoder_TIM3(void)
{

    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;                // Enable clock for TIM2                                               // TIM3->CR1 = 0;                                     // Disable timer
    TIM3->ARR = 73;
    TIM3->CCMR1 = TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_0; // Capture on TI1 and TI2
    TIM3->CCER &= ~(TIM_CCER_CC1P | TIM_CCER_CC2P);
    TIM3->SMCR = TIM_SMCR_SMS_1 | TIM_SMCR_SMS_0;      // Enable encoder mode
    TIM3->CR1 |= TIM_CR1_CEN;                          // Enable timer
    // Configure Pins 0 and 1 of Port A as alternate function inputs
    GPIOA->CRL &= ~(GPIO_CRL_CNF6 | GPIO_CRL_CNF7);
    GPIOA->CRL |= (GPIO_CRL_CNF6_1 | GPIO_CRL_CNF7_1);
    // Configure encoder interface
    TIM3->CNT = 36;                   // Reset cnt
}

void encoder_read(void)
{
	if (TIM3->CNT > 72)
	{
		TIM3->CNT = 72;
	}

	if (TIM3->CNT < 36)
	{
		TIM3->CNT = 36;
	}
	cnt = (uint8_t)((TIM3->CNT - 36) / 4);
}

void init_button(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN | RCC_APB2ENR_AFIOEN;	/*	Включаем тактирование порта C	*/
	AFIO->EXTICR[3] |= AFIO_EXTICR4_EXTI13_PC;					/*	Кнопка на PC13, поэтому настраиваем AFIO_EXTI4, соотв. этому порту	*/
	EXTI->IMR |= EXTI_IMR_MR13;									/*	Изначально все прерывания запрещены, поэтому надо в маску IMR в 13й бит записать 1	*/
	EXTI->FTSR |= EXTI_FTSR_TR13;								/*RTSR - прерывание по нарастанию, FTSR - прерывание по спаду*/
	/*Теперь каждый раз при нажатии кнопки будет генерироваться прерывание по спаду, и этот сигнал будет подаваться в контроллер прерываний - NVIC*/
	/*Но мы не разрешили NVIC их обрабатывать, поэтому он ничего не будет делать*/
	NVIC_EnableIRQ(EXTI15_10_IRQn);								/*Разрешили обработку прерываний с линий с 10 по 15*/
	NVIC_SetPriority(EXTI15_10_IRQn, 1);						/*Выставили единственному прерыванию самый большой приоритет*/
}

void EXTI15_10_IRQHandler(void)									/*Функция для обработки прерываний, вызывается автоматически*/
{
	if ((EXTI->PR & EXTI_PR_PR13) != 0)							/*PR - регистр, каждый бит которого соотв. флагу прерывания на опр. линии*/
	{
		delay(100);												/*Защита от дребезга*/
		if ((GPIOC->IDR & GPIO_IDR_IDR13) == 0)
		{
			TIM2->CR1 ^= TIM_CR1_CEN;							/*XOR (инвертирование) бита включения таймера*/
		}
		EXTI->PR |= EXTI_PR_PR13;								/*Очищаем флаг прерывания, чтобы не зайти в него повторно*/
	}
}

void TIM2_IRQHandler(void)
{
	LED_NUM_SWAP(led_num);
	TIM2->SR &= ~TIM_SR_UIF;									/*UIF - Update Interrupt Flag - программное очищение флага путем записывания нуля*/
}

void delay(uint32_t delay_value)
{
	for(uint32_t i = 0; i < delay_value; i++);
}

void init_clk(void)												/*Настройка внешнего генератора как источник тактирования на 64МГц*/
{
	// Enable HSI
	RCC->CR |= RCC_CR_HSION;
	while(!(RCC->CR & RCC_CR_HSIRDY)){};

	// Enable Prefetch Buffer
	FLASH->ACR |= FLASH_ACR_PRFTBE;

	// Flash 2 wait state
	FLASH->ACR &= ~FLASH_ACR_LATENCY;
	FLASH->ACR |= FLASH_ACR_LATENCY_2;

	// HCLK = SYSCLK
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;

	// PCLK2 = HCLK
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;

	// PCLK1 = HCLK
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;

	// PLL configuration: PLLCLK = HSI/2 * 16 = 64 MHz
	RCC->CFGR &= ~RCC_CFGR_PLLSRC;
	RCC->CFGR |= RCC_CFGR_PLLMULL16;

	// Enable PLL
	RCC->CR |= RCC_CR_PLLON;

	// Wait till PLL is ready
	while((RCC->CR & RCC_CR_PLLRDY) == 0) {};

	// Select PLL as system clock source
	RCC->CFGR &= ~RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SW_PLL;

	// Wait till PLL is used as system clock source
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL){};
}

void init_tim2()
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;		/*Включаем тактирование на шине APB1, на которой таймер*/
											/*Нужен 1Гц: делим 64МГц на 64000, потом на 1000*/
	TIM2->PSC = 64000 - 1;					/*Настройка Prescaler - предделитель*/
	TIM2->ARR = 1000;						/*ARR - Auto-Reload Register, задали 1Гц, т.е. 1с*/
	/*DIER - DMA Interrupt enable register, в нем бит UIE - Update Interrupt Enable - прерывание будет каждый раз при обновлении таймера*/
	TIM2->DIER |= TIM_DIER_UIE;
	TIM2->CR1 |= TIM_CR1_CEN;				/*CEN - cnt Enable, разрешаем подсчет*/
	NVIC_EnableIRQ(TIM2_IRQn);				/*Разрешаем NVIC обработку прерываний*/
	NVIC_SetPriority(TIM2_IRQn, 0);			/*Выставляем приоритет единицу*/
}

int main(void)
{
	init_clk();
	init_led_num();
	init_button();
	init_tim2();
	init_decoder_TIM3();
    while(true)
    {
    	encoder_read();
    	set_led_num(cnt);

    }
}




